// module.exports = (fileNumber, applicantName, applicantAddress, term, commencementDate, groundRent, landUse, regNum, page, volume, passportUrl, agency_logoUrl, bengisLogoUrl)
module.exports = inputData => {
  const { receiptDate, paymentDate, amount } = inputData;
  const copy = ['Original', 'Duplicate Copy', 'Merchant Copy'];
  let receipt = ``;
  copy.forEach(e => {
    receipt += `<hr>
    <div class="receipt">
        <section id="head">
            <div class="state-logo">
            <img id="state-logo-img" src="resources/img/state_logo.jpg" alt="state logo" />
            </div>
            <div class="agency-logo">
            <img id="agency-logo-img" src="resources/img/agency_logo.png" alt="Agency Logo" />
            </div>
            <P class="document-name">Revenue Receipt - ${e}</P>
            
        </section>
        <p class="receipt-number">Receipt Number:<span class="bold"> ${
          inputData.receiptNumber
        }</span></p>
        <p class="receipt-date">Receipt Date: <span class="bold">${new Date(
          receiptDate
        ).toLocaleString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric'
        })}</span></p>
        <section class="file-info">
            <p class="float-left">File Number: <span class="bold">${
              inputData.fileNumber
            }</span></p>
            <p class="float-right"><span class="bold">${
              inputData.paymentMode
            } N0: </span><span class="bold">${
      inputData.paymentRefNumber
    }</span></p>
            <p class="center-float">Bank Name: <span class="bold">${
              inputData.bankName
            }</span></p>
            
            
        </section>
        <section class="revenue-statement">
            <div class="content">
                <p class="float-left"> <span class="description">Received From</span>  <span class="bold">${
                  inputData.receivedFrom
                }</span> </p>
                <p class="float-right">Payment Date <span class="bold">${new Date(
                  paymentDate
                ).toLocaleString('en-GB', {
                  day: 'numeric',
                  month: 'short',
                  year: 'numeric'
                })}</span> </p>
            </div>
            <p class="content clear-float"><span class="description">the sum of</span>  <span class="bold big-font ">${
              inputData.amountInWord
            } </span> </p>
            <p class="content"><span class="description">being payment for</span>  <span class="bold">${
              inputData.paymentFor
            }</span> </p>
            <p class="content"><span class="bold big-font">${amount.toLocaleString(
              'en-NG',
              {
                style: 'currency',
                currency: 'NGN',
                currencyDisplay: 'symbol'
              }
            )}</span> </p>
            <div class="float-right">
                <p class="content">Generated By: <span class="bold">${
                  inputData.generatedBy
                }</span> </p>
            </div>
        </section>

    </div>`;
  });

  return `
  <!DOCTYPE html>
  <html lang="en">
  
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Receipt</title>
      <style>
          *{
      padding: 0;
      margin: 0;
      font-size: 8pt;
  }
  
  .bold{
      font-weight: bolder;
  }
  
  .container{
      position: relative;
      font-weight: 400;
      font-family: Arial, Helvetica, sans-serif;
      height: 27cm;
      width: 17cm;
      margin: 0.6cm auto;
  }
  
  .receipt{
      position: relative;
      height: 7cm;
      padding: 20px 0;
      margin: 16px 0;
      border-bottom: black 2px solid;
  }
  
  #head{
      height: 2cm;
  }
  
  .state-logo, .float-left{
      float: left;
  }
  
  .agency-logo, .float-right{
      float: right;
  }
  
  .center-float{
      text-align: center;
  }
  
  
  #state-logo-img{
      display: block;
      border: rgb(0, 0, 0) solid 2px;
      height: 65px;
      width: 65px;
  }
  
  .document-name{
      text-align: center;
      font-weight: bolder;
      font-size: 1.1em;
      padding-top: 25px;
  }
  
  #agency-logo-img{
      display: block;
      border: rgb(0, 0, 0) solid 2px;
      height: 30px;
      margin-top: 17px;
      width: 100px;
  }
  
  .receipt-number, .receipt-date{
      position: relative;
      top: -15px;
      font-size: 0.8em;
      text-align: right;
  }
  
  .file-info{
      margin: 20px 0;
  }
  
  .big-font{
      font-size: 1.1em;
  }
  
  .content{
      padding: 4px 0;
      height: 12px;
      border-bottom: 1px dashed #000000;
  }
  
  .description{
      display: inline-block;
      width: 100px;
      margin-right: 10px;
  }
  
  .clear-float{
      clear: both;
  }
  
  .key{
      width: 2cm;
  }
  
  .value{
      width: 3cm;
  }
      </style>
  </head>
  
  <body>
      <div class="container">
        ${receipt}
      </div>
  </body>
  </html>
    `;
};
